### ISSUE TITLE
注文管理の項目　名前変更と追加

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#11]
[名前変更]
生産＆発注　→　発注履歴
新規　　　　→　新規発注
デザイン　　→　グッズデザイン

[追加]
ユーザー情報　　… 今の発注者情報を表示
お届け先リスト　… 新しく追加

**Comment by alexeypolitov** [comment]
@take-iwa 
> [名前変更]
> 生産＆発注　→　発注履歴
> 新規　　　　→　新規発注
> デザイン　　→　グッズデザイン

変更しました。

> [追加]
> ユーザー情報　　… 今の発注者情報を表示
Addressesとして追加しました
> お届け先リスト　… 新しく追加
Clientsとして追加しました

**Comment by take-iwa** [comment]
@alexeypolitov 
＜名前変更＞
Addresses　→　ショップ情報
Clients →　お届け先リスト

＜修正＞
■Addresses(ショップ情報)の内容をちょっと変更したく。
入力項目は、こちら
`種類、ショップ名、URL、お問い合わせ先(電話番号またはメールアドレス)、納品書メッセージ`

"種類"の内容(選択式)
```
BASE
STORES.jp
minne
Creema
Booth
Yahoo!ショッピング
SPIKE
VILLAGE VANGUARD
楽天
自社サイト
その他
```
■今、Addressesに入っている住所情報は、右上メニュー→アカウント情報の戻してください。すみません。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
