### ISSUE TITLE
発注者情報　項目追加１

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#12]
発注者(ユーザー)情報に、ショップ情報を追加してください。

内容は、例のように。
種類は、どこのECサイトなのか。
今のところ、BASEやSTORE.jpとは連携させます。

ショップ情報例↓
<img width="1216" alt="2017-07-19 19 08 37" src="https://user-images.githubusercontent.com/23730555/28361999-bbefbaca-6cb5-11e7-8b45-a4de397775d1.png">

種類の選択項目↓
<img width="261" alt="2017-07-19 19 12 52" src="https://user-images.githubusercontent.com/23730555/28362143-5786bbd2-6cb6-11e7-9167-33922f234042.png">

**Comment by tomoyuki1110** [comment]
BASE,STORE.jp

**Comment by take-iwa** [comment]
■Addresses(ショップ情報)の内容をちょっと変更したく。
上と同じですが、入力項目あげておきます。
`種類、ショップ名、URL、お問い合わせ先(電話番号またはメールアドレス)、納品書メッセージ`

"種類"の内容(選択式)
```
BASE
STORES.jp
minne
Creema
Booth
Yahoo!ショッピング
SPIKE
VILLAGE VANGUARD
楽天
自社サイト
その他
```

■今、Addressesに入っている住所情報は、右上メニュー→アカウント情報の戻してください。すみません。

**Comment by alexeypolitov** [comment]
@take-iwa こちらはapi連携は追加となります。宮本さんに相談済みです。なので、それ以外どの項目を追加すればいいのか教えて下さい

**Comment by take-iwa** [comment]
@alexeypolitov 大岩が書いた一つ前のコメントの内容は追加してください。
API連携は関係なく、入力項目の修正です。

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov ショップ情報に必要なのは下の５つ。
ショップ名
種類
URL
お問い合わせ先(電話番号またはメールアドレス)
納品書メッセージ


下の項目はショップ情報には入れず、アカウント情報で入力させてください。
　電話番号
　メールアドレス
　郵便番号
　都道府県
　市町村区番地
　建物名
<img width="497" alt="2017-09-11 15 48 38" src="https://user-images.githubusercontent.com/23730555/30261677-c098d8c2-9708-11e7-8bf4-974bd4eb1dd6.png">

**Comment by alexeypolitov** [comment]
@take-iwa わざと住所は別のところにいつしました。なんで今変更しないといけないのか教えてください

**Comment by take-iwa** [comment]
@alexeypolitov すみません。ショップ情報の住所入力はこちらの指示でした。申し訳ないです。

住所そのままでいいんですが、
お問い合わせ先　と　電話番号、メールアドレス　の項目がかぶっているので、
お問い合わせのみ残して、
個別にある「電話番号」と「メールアドレス」を削除してください。
