### ISSUE TITLE
お届け先リストの作成

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#13]
注文管理項目に追加する「お届け先リスト」について

発注者のお客様リストです。

フィールドは、
・氏名
・郵便番号
・住所　　　　・・・入力時は郵便番号から途中まで自動で入るように
・電話番号

**Comment by take-iwa** [comment]
発注する時は、自由入力の他にこのリストから選択できるようにする。

**Comment by alexeypolitov** [comment]
@take-iwa 自動入力以外追加しました

**Comment by take-iwa** [comment]
@alexeypolitov 内容OKです。
ただ、登録時に”建物名”まで入力しないと保存できないので、
”建物名”をなくても登録できるようにお願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
