### ISSUE TITLE
発注者情報　項目追加２

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#15]
発注者自身の住所を複数登録できるようにする。

発注する際は、依頼主住所を
・受注者情報の住所リスト
・住所がバレたくない人用のレンタルオフィス住所
から選択できるようにする。

**Comment by tomoyuki1110** [comment]
重要：ユーザが入れれる
デフォルトの住所

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 追加しました

**Comment by take-iwa** [comment]
@alexeypolitov Adresses確認できましたが、申し訳ないです。
住所情報はユーザー情報に紐付く１つだけで大丈夫でした。
住所情報でなくショップ情報にします。詳しくは、こっちです。https://github.com/DecodeLLC/canvath-web/issues/12
