### ISSUE TITLE
BASEとのAPI連携

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#16]
BASEとのAPI連携お願い致します。
https://developers.thebase.in/

**Comment by take-iwa** [comment]
Budgetsで商品作成 → BASEに出品ボタン → 連携！ → BASE のストアに商品追加
※元ネタのキャンバスもそうですが、BASEでの注文を自動で発注することはできないようです。商品の追加まで。

API使用の申請が必要
　https://developers.thebase.in/apply
　<アプリ情報>
　　・アプリ名
　　・アプリの説明
　　・アプリURL
　　・コールバックURL
　　・アプリのロゴ画像
　　・利用権限
　　・検索APIの利用
　<開発者情報>
　　・法人名
　　・担当者名
　　・住所
　　・電話番号
　　・メールアドレス

　ドキュメントはこちら
　https://github.com/baseinc/api-docs

ちなみにキャンバスでの必要な利用権限はこれらでした。
・ユーザー情報を見る
・ユーザーのメールアドレスを見る
・商品情報を見る
・注文情報を見る
・引き出し申請情報を見る
・商品情報を更新する
・注文情報を更新する

**Comment by alexeypolitov** [comment]
@take-iwa baseのアカウントを共有していただけますか？
