### ISSUE TITLE
決済は下記を使います。

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#17]
クレジットカード
コンビニ
GMOペイメント
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
後払い決済
後払いドットコム
=========================================
Amazonpay
Amazon
=============================================

**Comment by tomoyuki1110** [comment]
銀行振込

**Comment by take-iwa** [comment]
■後払いドットコムについて
https://www.atobarai.jp/member/login/login
　サイトの追加は、
　　①サイトへの後払いに関する定型文の掲載
　　　　→「特定商取引法」および「決済方法選択画面」に掲載していただく文面
　　　　　　http://www.ato-barai.com/for_shops/tokuteishou.html
　　②後払いドットコムへのサイト追加申請
　　③審査・利用開始

■GMOペイメントについて
テスト環境での使用可能
　サイト管理画面
　https://kt01.mul-pay.jp/mulpayconsole/site/tsite00026551/

　ショップ管理画面
　https://kt01.mul-pay.jp/mulpayconsole/shop/tshop00029449/
　
　ドキュメントは、管理画面右上のメニューから入手できます。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa apiチェック中です。月曜日に返答します。

**Comment by take-iwa** [comment]
[決済について.txt](https://github.com/DecodeLLC/canvath-web/files/1263823/default.txt)

**Comment by alexeypolitov** [comment]
@take-iwa こちらは #60 と同じのようなのでクローズしてもいいですかね？
