### ISSUE TITLE
納品書

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#18]
CANVATHのように

依頼者の名前
発送者の名前を入れたら、
それで納品書がプレビューでみれると同時に、
商品発送時に納品書が発行できるようにお願い致します。
![2017-07-19 20 24 06](https://user-images.githubusercontent.com/17405609/28364653-57b35084-6cc0-11e7-92b9-722a30551685.png)
![2017-07-19 20 24 47](https://user-images.githubusercontent.com/17405609/28364652-57b249d2-6cc0-11e7-8835-bc55f8f426c1.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 納品書自体プレビューできるようにしました。正しいフォーマットをいただいた上でどの部分を自由で変更可能にするのかまとめてアップお願いします。

**Comment by take-iwa** [comment]
@alexeypolitov プレビューは、出なかったですね。フォーマットと変更可能部分は、まとめます。
<img width="776" alt="2017-08-25 14 56 08" src="https://user-images.githubusercontent.com/23730555/29701269-b75c8e40-89a5-11e7-9cba-63f9e8f5c1e0.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov プレビュー確認しました。
この納品書は直接エンドユーザに届くものなので、値段と丸井の情報は記載しません。
発注者の情報とお届け先・商品の情報のみとなります。
見づらいかもしれませんが、ご確認ください。
[59a6b80938a18 2.pdf](https://github.com/DecodeLLC/canvath-web/files/1263762/59a6b80938a18.2.pdf)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov いつくか修正点です。
・納品書メッセージ大きく
・この度は<ショップ名>をご利用いただき...
・最後の一文削除

<img width="374" alt="order_act_ _ _ _issue__38_ _decodellc_canvath-web" src="https://user-images.githubusercontent.com/23730555/30262584-71aa3fd6-970c-11e7-9b46-8bb1693d88d5.png">

**Comment by alexeypolitov** [comment]
@take-iwa 
> ・納品書メッセージ大きく

何パーセント大きくすればいいですか？

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa メッセージフォントサイズ以外修正しました。

>・納品書メッセージ大きく

何パーセント大きくすればいいですか？

**Comment by take-iwa** [comment]
注文履歴から納品書・領収書ダウンロードできません。
<img width="264" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30605427-fad8314e-9da8-11e7-99be-8849ef7c5f78.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
