### ISSUE TITLE
デザーンツールを使わずにアイテム変更できるようにする

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#20]
up-tでもあると思いますが、
デザインツールを使わなくても同じデザインでアイテムだけ変更して登録できるようにする。

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました。

<img width="918" alt="screen shot 2017-08-19 at 13 54 05" src="https://user-images.githubusercontent.com/3468058/29483654-e1a81a80-84e5-11e7-91bc-034d80b65e68.png">

**Comment by take-iwa** [comment]
@alexeypolitov 確認しました。
色の変更：ツール上では変更されていますが、アイテム画像が変更できていません。
アイテム変更：できませんでした。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
