### ISSUE TITLE
新規登録時にメール返信がくるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#22]
新規登録時に、仮登録のメール返信が来るように。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 追加しました。場合によって迷惑メールに入ってることもあります。それから正しいメールのフォーマットをください

**Comment by take-iwa** [comment]
@alexeypolitov メール来ないです。確認お願いします。
日本時間　8/25 15:40頃　oce18ea7imj4@sute.jp

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました。メールが迷惑に入る可能性があります

**Comment by take-iwa** [comment]
@alexeypolitov メールきました。文章は#31 にて。
