### ISSUE TITLE
送料、後払い決済手数料の設定ができるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#23]

**Comment by tomoyuki1110** [comment]
各県ごとに、送料を入れられると同時に
◯◯円以上は送料無料

の設定ができるように

後払い決済手数料は
◯◯円と設定した上で
◯◯円以上は無料

と設定できるように

**Comment by alexeypolitov** [comment]
@take-iwa こちらは詳しく説明していただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov 
こちら全てadminに追加してください。
イメージはup-tの管理画面＞システム設定です。

<送料>
■送料設定
　├ 北海道
　├ 青森県
　├ 岩手県
　・
　・
　・

　都道府県毎に送料を設定できるようにしてください。
　購入金額〇〇円以上で送料無料にできるようにしてください。


<手数料>
■後払い決済手数料
　購入金額〇〇円以上で手数料にできるようにしてください。

■代引き手数料
　これは一律です。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
