### ISSUE TITLE
管理画面内で、プレビューの画像を取得できるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#25]
販売者さんようにプレビュの画像を取得できるように

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 追加しました。

<img width="544" alt="screen shot 2017-08-19 at 14 09 28" src="https://user-images.githubusercontent.com/3468058/29483710-0a7f01ec-84e8-11e7-88bd-0d9b788740cf.png">
