### ISSUE TITLE
Printtyへ送るときにメールが飛ぶように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#26]

**Comment by tomoyuki1110** [comment]
購入時、購入決定時、Printtyアップロード時、送付時にメールが飛ぶように

また、マスター画面でメールを変更できるようにお願いします。

**Comment by tomoyuki1110** [comment]
また上記は購入者に送るメールです、
今回は、送付者と購入者が別なので
送付者にも送付時にメールが行くようにお願い致します。

**Comment by tomoyuki1110** [comment]
購入：依頼者
決済完了：依頼者
Prinnttyへのアップ：依頼者
Printtyからの戻り：依頼者＋購入者（メアドがある時）

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov printtyアップロード時のメールが来ないです。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov すぐにアップロードエラーになります。確認お願いします。

<img width="303" alt="canvath_admin_web" src="https://user-images.githubusercontent.com/23730555/31606545-56e5aa88-b2a4-11e7-848f-615fb46d4445.png">

**Comment by alexeypolitov** [comment]
@take-iwa printty側の問題でした。修正しました。ご確認ください。
ちなみに、printtyの本番にアップするようになってます
