### ISSUE TITLE
admin画面で配達先情報が一部出ない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#30]
発注者が入力した情報
<img width="454" alt="2017-08-25 14 46 55" src="https://user-images.githubusercontent.com/23730555/29701186-2cfc72b0-89a5-11e7-83de-3eb3b0d6066b.png">
↓
admin画面の情報
<img width="317" alt="2017-08-25 14 54 02" src="https://user-images.githubusercontent.com/23730555/29701204-43a40816-89a5-11e7-8c92-ac69aa23ef40.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
