### ISSUE TITLE
メール文章対応

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#31]
@alexeypolitov 各種メールのフォーマット用意します。お待ちください。

**Comment by alexeypolitov** [comment]
@take-iwa こちらはいかがですか？

**Comment by take-iwa** [comment]
メールこちらです。
[budgets_mail.zip](https://github.com/DecodeLLC/canvath-web/files/1265501/budgets_mail.zip)

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました

**Comment by take-iwa** [comment]
@alexeypolitov コンビニ決済のメール文章ミスってました。すみません。
こちらに直してください。
[03-1_購入時自動送信(コンビニ決済).txt](https://github.com/DecodeLLC/canvath-web/files/1292468/03-1_.txt)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
コンビニ払いなくなったので、閉じます。
