### ISSUE TITLE
決済方法で代引きを選べる条件

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#32]
決済方法で「代金引換」を選択できるのは、
ご依頼主とお届け先が同じ場合のみにしてください。
(発注者が自分宛に送るパターン)

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました

**Comment by take-iwa** [comment]
[お届け先を自分にする]

**Comment by alexeypolitov** [comment]
@take-iwa こちらは住所を入れる時にチェックボックでいいですか？

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
