### ISSUE TITLE
発注フローの改善

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#33]
今のところ、発注するフローでユーザーの手間が多いので改善したい。

注文追加をクリック
↓
お届け先設定　・・・タイトル入力は無くす
　　　　　　　・・・ショップを選べるようにする
<img width="254" alt="_2017-08-31_0_58_45" src="https://user-images.githubusercontent.com/23730555/29882391-cfe94638-8de7-11e7-8733-4dcba6eb0c97.png">
↓
グッズデザイン一覧　・・・グッズデザイン一覧で画像クリックしたら、すぐ「Add to order」が開く
↓
アイテム追加・・・タイトルは「アイテム追加」に変更
　　　　　　　・・・ここの"Add to order"で注文番号選択しなくても"次へ"で目的の注文に追加する
　　　　　　　・・・”次へ”クリックで注文管理画面へ移動する
<img width="263" alt="_2017-08-31_1_01_29" src="https://user-images.githubusercontent.com/23730555/29882666-b672595a-8de8-11e7-8617-0a88d8c87a00.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。
