### ISSUE TITLE
グッズデザイン画像クリックで出るメニュー日本語化

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#35]
<img width="148" alt="2017-08-31 1 19 18" src="https://user-images.githubusercontent.com/23730555/29883206-7e0f9684-8dea-11e7-8f62-1d6d1836f173.png">

Edit design 　　　　デザイン編集
Add to order 　　　  注文にアイテム追加
Change color 　　　カラー変更
Change substrate 　アイテム変更
Delete 　　　　　　  削除

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました
