### ISSUE TITLE
発注履歴の画面の変更

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#37]
発注履歴一覧で見られる項目を変更したい。

<一覧で見られる項目>
　   ・注文ID
　   ・発注日
　   ・発注商品
　 　　　→アイテム種類　x　個数
　   ・注文ステータス
new・合計金額
　   ・支払い方法
new・配達伝票番号
　　　　→番号クリックで配送会社の配送状況確認ページへ
　   ・詳細ボタン
　　　　＜詳細情報＞
　　　　　→詳細情報にショップ名を追加
　　　　　→右上メニューは”納品書ダウンロード”ではなく、”領収書ダウンロード”

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました
