### ISSUE TITLE
発注履歴からの領収書ダウンロード

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#38]
発注履歴からダウンロードできるのは、”領収書”のみ。
フォーマットは、up-tやcouple-tの納品書と同様でいいのですが、
”納品書”ではなく、”ご注文内容”にしてください。

表の項目は、
アイテム｜単価｜数量｜総額

発行元のバジェッツの情報
```
Budgets
https://budgets.jp
丸井織物株式会社
〒150-0001
東京都渋谷区神宮前三丁目25-6
サンビューティ原宿2F
Email: info@gudgets.jp
```

アイテムの取り扱い説明は、領収書なので不要です。。

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました

**Comment by take-iwa** [comment]
@alexeypolitov 
領収書なので、決済が完了した後に見られるようにしてください。
完了するまでは、メニューでクリックしても
「決済完了後にご利用になれます」
と出してください。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 決済済み注文の領収書が見られません。
確認お願いします。
<img width="415" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30729696-72900c8a-9f9c-11e7-869d-c1c0a00a8ac8.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
