### ISSUE TITLE
管理者あてのメールが購入者に送られている

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#40]
購入者に管理者用のメールが送られてます。
<img width="391" alt="2017-09-11 15 59 17" src="https://user-images.githubusercontent.com/23730555/30262053-4c3cb2da-970a-11e7-8301-de93a3aab3d2.png">

以前送ったメール文章リストには、購入者向けのメールと管理者向けのメールがあります。
メールの送り先分けてください。

＜購入者向け＞
01-1_購入時自動送信(銀行振込).txt
02-1_購入時自動送信(カード払い).txt
03-1_購入時自動送信(コンビニ決済).txt
05-1_購入時自動送信(AmazonPay).txt
06-1_購入時自動送信(代金引換).txt
11-1_決済時自動送信(銀行振込).txt
12-1_決済時自動送信(コンビニ決済).txt
21_printtyアップロード時自動送信.txt
31-1_発送時自動送信(佐川急便).txt
31-2_発送時自動送信(ヤマト運輸).txt

＜管理者向け＞
01-2_購入通知(銀行振込).txt
02-2_購入通知(カード払い).txt
03-2_購入通知(コンビニ決済).txt
04-2_購入通知(コンビニ後払い).txt
05-2_購入通知(AmazonPay).txt
06-2_購入通知(代金引換).txt
12-2_決済通知(コンビニ決済).txt

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました

**Comment by take-iwa** [comment]
@alexeypolitov 銀行振込の場合にユーザーに正しいメールのみがくるのは、確認しました。
カード・Amazonは途中でエラーとなるので未確認。
代金引換は、メールが来ていないように思います。

**Comment by take-iwa** [comment]
@alexeypolitov 代金引換のメール確認できました。

**Comment by take-iwa** [comment]
@alexeypolitov カード払いのメール確認しましたが、こちらも手数料が英語になっています。
こちらは、
Payment fee　=　手数料

```
【BUDGETS】ご注文ありがとうございます
# --------------------------
[owner_company]
[owner_name]　様

BUDGETSカスタマーサポートです。
この度は、ご注文いただき誠にありがとうございます。

以下の内容でご注文を承りました。

------------------------------------------------------------------
本メールはシステムにより自動で送信させて頂いております。
このままご返信いただいてもお答えできません。
------------------------------------------------------------------

▼ご注文日時
[regist]

-------------------------
【ご注文内容】
-------------------------
▼ご注文番号
[pay_num]

▼ご注文商品
[pay_item]

▼お支払い方法
カード決済

▼ご請求金額

商品合計：[pay_price]円
割引：[pay_discount]円
送料：[pay_postage]円
手数料：[pap_fee]円
消費税：[pay_tax]円

ご請求金額：[pay_total]円

※クレジットカードにて代金をご請求させて頂きます。

▼備考
[remarks]

-------------------------
【配送先】
-------------------------
▼氏名
[client_name]

▼氏名（フリガナ）
[client_name_ruby]

▼郵便番号
[client_add_num]

▼住所
[client_add_text]

▼電話番号
[client_tel]


今後とも、BUDGETSをご愛顧賜りますよう、
よろしくお願い申し上げます。

☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★
Budgets(バジェッツ)カスタマーサポート
https://up-t.jp

facebookページ
https://www.facebook.com/budgets/

お問合せ：info@budgets.jp

☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★

Puroduced by
丸井織物株式会社
```

**Comment by take-iwa** [comment]
@alexeypolitov Amazon Payでの支払いの場合、メールが来ないようです。確認お願いできますか？

<img width="515" alt="canvath_admin_web" src="https://user-images.githubusercontent.com/23730555/30902411-1fa8254e-a3a6-11e7-840e-bcae0882ad57.png">
