### ISSUE TITLE
注文番号の扱いについて

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#41]
すみません。大岩の指示がわかりづらかったです。。
budgets内の注文番号　と　納品書に記載する発注者が任意で入力する注文番号　は別物です。

budgets内の注文番号は、これまで通り自動生成してください。

納品書に記載する発注者が任意で入力する注文番号は、納品書のみに使う番号でbudgetsの管理には使いません。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
