### ISSUE TITLE
注文作成時に納品書のプレビューが見られるようにする

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#42]
注文前のメニューからの納品書のプレビューを見られるようにしてください。

<img width="1224" alt="2017-09-11 16 33 36" src="https://user-images.githubusercontent.com/23730555/30263299-5b6ccf6a-970f-11e7-96e4-0d2653944347.png">

**Comment by alexeypolitov** [comment]
@take-iwa どのプレビューですか？

**Comment by take-iwa** [comment]
@alexeypolitov 
納品書です。
おそらく今だと管理画面でしか見られないと思うのですが、注文者がエンドユーザーの元に納品書が届けられる前に確認できるようにしたく。

<img width="766" alt="2017-09-11 20 18 46" src="https://user-images.githubusercontent.com/23730555/30272279-b336df50-972e-11e7-87ad-1f7b62f659fd.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
@alexeypolitov どこから納品書プレビュー見られますか？

**Comment by alexeypolitov** [comment]
@take-iwa 注文は支払い済みになるまで納品書を見れないです

**Comment by take-iwa** [comment]
@alexeypolitov メニューに「納品書ダウンロード」はあるのですが、しばらくしてエラーになります。
また、管理画面でも納品書ダウンロードできないようです。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
