### ISSUE TITLE
注文情報の配達伝票番号

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#44]
注文後、すぐ番号が発行されていますが、
注文直後は

発送後にご確認できます

として、
工場で発送されたら、伝票番号を入れるようにお願いします

<img width="479" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30364133-e5eadd64-989d-11e7-807c-93fd2a26489b.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
