### ISSUE TITLE
空のメールが届く

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#48]
おそらく注文時のメールだと思いますが、内容が空のメールが届きました。
確認お願いいたします。

<img width="279" alt="_ _google 851" src="https://user-images.githubusercontent.com/23730555/30366456-0c81ec44-98a6-11e7-9ff4-a0749472e8a4.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
