### ISSUE TITLE
注文作成時に納品書のプレビューが見られるようにする

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#52]
注文作成して支払う前に納品書を確認できるようにお願いします。

**Comment by take-iwa** [comment]
@alexeypolitov わかりづらくて申し訳ないです。
支払い後にしか確認できないようにしたかったのは、領収書の方のみです。
ですので、納品書に関しては、支払い前に確認できるようにしたく。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
