### ISSUE TITLE
支払いの名前と順番

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#53]
現金払い
↓
代金引換

＜順番＞
クレジットカード払い
代金引換
コンビニ後払い
AmazonPay
銀行振込
コンビニ決済

**Comment by alexeypolitov** [comment]
@take-iwa コンビニ後払い/コンビニ決済はなしではなかったですか？今pay.jpを設定してますので

**Comment by tomoyuki1110** [comment]
コンビニ後払いはあり

コンビニ払いはなし

です

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。「コンビニ後払い」は作業中です。そのために別のタスクが登録されてると思います
