### ISSUE TITLE
新規注文のレイアウトと文言

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#54]
左上の[注文追加]
↓
新規注文追加

注文する
↓
お支払いへ

レイアウトについて
<img width="628" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30582017-2d383f40-9d5d-11e7-8aba-554319096428.png">

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov レイアウトok.
文言の変更もお願いします。

> 左上ボタンの`注文追加`
> ↓
> `新規注文追加`



> `注文する`
> ↓
> `お支払いへ`

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
