### ISSUE TITLE
ショップ情報登録でダミー住所を選択できるようにして欲しい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#56]
ショップ情報を入力する時に
住所を知られたくないオーナーのためにレンタル住所を選択できるようにする。

レンタル住所は、最初は丸井の東京営業所にしておいてください。

この住所は、管理画面で変更できるように設定に追加お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov チェックボックス名は、`レンタル住所を使う`

レンタル住所を選択した場合、
　郵便番号
　都道府県
　市町村区番地
　建物名
のみに入力が反映されるようにお願いします。

<img width="263" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30945855-8851a5bc-a43b-11e7-974d-702279c1b5e3.png">

<img width="252" alt="banners_and_alerts_ _canvath" src="https://user-images.githubusercontent.com/23730555/30945967-2478ef18-a43c-11e7-8426-cf28092d3336.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
