### ISSUE TITLE
支払い時に発注内容確認画面を出すように

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#57]
１）「保存」→　確認画面へ　　　にボタンの文言変更

２）「確認画面へ」を押した後、
注文内容、選択した支払い方法を表示し、
　　注文を確定する
　　戻る
のボタンをつける。
「注文を確定する」を押した後、発注履歴画面に遷移。
「戻る」で支払い方法選択に戻る。

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 確認画面が増えているのはOKなのですが、支払い方法選択タイミングとしてはカード払いやAmazonPayの場合を考えると確認画面の方になりますよね・・。

そうしましたら、ボタンの文言を変更願います。

最初の画面。　`確認画面へ`　→　`支払い方法選択へ`
<img width="258" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30840518-b817d8c8-a2b2-11e7-9aac-97ad23f7a165.png">

次の確認画面。　そのままでOK.

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
