### ISSUE TITLE
スマホ表示になった時、グローバルナビゲーションの幅が合っていない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#58]
トップのメニューの幅が合っていないのか、
日本語化のボタンがずらさないと見えない。

<img width="218" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30629087-e5806976-9e14-11e7-8289-c753813257f3.png">

**Comment by alexeypolitov** [comment]
@take-iwa 変更しました。EN/JAはメニューに移動しました
