### ISSUE TITLE
課金にコンビニ後払いを入れる

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#60]
コンビニ決済は必要ないですがコンビニ後払い(後払いドットコム)は繋ぎ混んでください。

**Comment by alexeypolitov** [comment]
@take-iwa 対応しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov @tomoyuki1110 後払いを選択して購入はできるのですが、後払いドットコムでの決済確認はランディングページなど出来上がっていないと許可が下りないため、まだ確認できていません。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境で確認してます。
送料は、「送料」の項目に、
消費税は、「手数料」の項目に入れていただけますか？
<img width="405" alt="_com ___" src="https://user-images.githubusercontent.com/23730555/31879224-bb842992-b817-11e7-8333-1210995430cb.png">

**Comment by take-iwa** [comment]
後払いドットコムへの
　新規注文 → 申請OK
　注文キャンセル → キャンセル申請OK
　出荷csvアップ → 配送番号の反映OK

残り、ステータス切り替え
