### ISSUE TITLE
削除したはずのアイテムが注文に入っている

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#62]
<img width="512" alt="canvath_admin_web" src="https://user-images.githubusercontent.com/23730555/30798922-23e43fbc-a216-11e7-9b42-caf6890546d2.png">
<img width="483" alt="canvath_admin_web" src="https://user-images.githubusercontent.com/23730555/30798965-42097eb2-a216-11e7-8cbe-b636bda2a047.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov どうもまた削除したアイテムが入っているようで。確認お願いします。
注文内容
<img width="250" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30966737-ea743a44-a494-11e7-84ef-930ef6096d34.png">

printty内
![printty](https://user-images.githubusercontent.com/23730555/30966746-f2bcb406-a494-11e7-9e93-cdf125453f10.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
