### ISSUE TITLE
新規注文追加画面の文言修正

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#67]
注文番号
　↓
`納品書に記載する注文番号`

注文日
　↓
`納品書に記載する注文日`

<img width="278" alt="canvath" src="https://user-images.githubusercontent.com/23730555/30895060-a80c904c-a382-11e7-8d2a-34e20f34ae2a.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
