### ISSUE TITLE
注文ステータス　再日本語化

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#68]
注文ステータスが戻ってます。

都合の良い時に変更お願いします。
```
Waiting for payment
Payment confirmed
Printty uploading
Shipped
Cancelled

↓

決済待ち
決済完了
アップロード中
出荷済み
キャンセル済み
```

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 大岩のミスです。すみません。ごめんなさい。

Printty uploading
　↓
~~生産中~~
　↓
`生産アップロード中`

**Comment by alexeypolitov** [comment]
@take-iwa いまこういう風になってます。いかがですか？

Unchecked order - 制作中
Waiting for payment - 決済待ち
Payment confirmed  - 決済完了
Printty uploading - 生産アップ中
Uploading failed - 生産アップエラー
Printty uploaded - 生産中
Shipped - 出荷済み
Cancelled - キャンセル済み


**Comment by take-iwa** [comment]
@alexeypolitov 大丈夫ですね。すみません。
