### ISSUE TITLE
追加したアイテムの画像をダウンロードできるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/canvath-web#76]
デザイン追加
カラー追加
アイテム変更

のしたに

画像ダウンロード

と入れて下さい。

**Comment by take-iwa** [comment]
グッズデザインのアイテムクリックで表示される項目に、
"商品画像ダウンロード"
を追加してほしい。

"商品画像ダウンロード"を押したときに
デザインしたアイテムside毎のプレビュー画像をダウンロードできるようにお願いします。

この機能は、発注者が自分のサイトに商品追加するときにダウンロードした商品画像を使えるようにするためです。

**Comment by alexeypolitov** [comment]
@take-iwa 説明ありがとうございます。この機能の話は初めてなのでなしでお願いします

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 宮本さんの依頼でbase連携の代わりにこのタスクをやります

**Comment by take-iwa** [comment]
@alexeypolitov グッズデザインから画像ダウンロードするとファイル名がおかしく閲覧できません。

<img width="317" alt="canvath" src="https://user-images.githubusercontent.com/23730555/31868797-ecdb6d32-b7dd-11e7-8d0f-08717cc920c2.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
