### ISSUE TITLE
注文詳細＞注文番号の文言

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/canvath-web#80]
budgetsの注文番号、注文日に「納品書に記載する」が入っているので、「budgets」に修正お願いします。

それと、発送予定日はどうやって計算してますでしょうか？

<img width="247" alt="canvath" src="https://user-images.githubusercontent.com/23730555/31868900-ef61d5e0-b7de-11e7-946e-4764bae48522.png">

**Comment by alexeypolitov** [comment]
> budgetsの注文番号、注文日に「納品書に記載する」が入っているので、「budgets」に修正お願いします。

@take-iwa 修正しました
